### ISSUE TITLE
Genotype labels

### ISSUE THREAD

**Issue by SolayMane** [JimWhiting91/genotype_plot#15]
Thank you for the nice tool. I'm wondering if there is a possibility to adjust the size of the labels and also to add those labels to the dendrogram:
![image](https://user-images.githubusercontent.com/22656460/194580218-b3e2fb85-23fe-4f60-b307-54204a154e2b.png)
![image](https://user-images.githubusercontent.com/22656460/194580288-f2802e7a-6bcc-4d42-a325-5978b83cdd6c.png)

**Comment by JimWhiting91** [comment]
Hey,

So if you've saved your plot to the object `my_plot`, the heatmap is stored in the `my_plot$genotypes` slot. This is a normal ggplot object, so you can edit it using the usual ggplot approach, e.g. to reduce the size of y axis text...
```
 my_plot$genotypes = my_plot$genotypes + theme(axis.text.y = element_text(size = 8))
```
This will reassign the `genotypes` slot with a new heatmap with reduced text size.

There is information in the readme on how to add tip labels to the dendrogram, but the principles are the same, it's a ggtree object that you can edit and reassign. You can't add the same labels as are plotted in your above figure because the clustering rearranges individuals so they may no longer be in the populations defined in the popmap. For cases like yours where it looks as though you have many tips, I would opt to assign population colours, and plot coloured points at each tip. This just saves having lots of cluttered text. For e.g.
<img width="538" alt="image" src="https://user-images.githubusercontent.com/36704098/195807702-0e8e5d92-6b7e-421b-9813-686437446377.png">

Hope this helps!
Jim
