### ISSUE TITLE
Fail to open vcf.gz: could not load index

### ISSUE THREAD

**Issue by HanXiaoEvo** [JimWhiting91/genotype_plot#2]
Hi Jim,

First of all, thank you very much for making this nice function!

I am trying to apply it to my project right now but there is one major error that I can not fix, although which may not directly be related to the function (I do googled hard but still no idea).

My dataset is generated by ddRAD and the vcf file was made by the populations program in STACKS. The samples were all reference mapped but the genome is under scaffold stage.

I first bgzip my vcf and then as it asked for index, I did one using bgzip -i to make a vcf.gz.i. However the function didn´t take it so I tried again with bcftools index, then the error is 
Chromosome blocks not continuous
index: failed to create index 

So I am wondering what I should do now, any suggestions will be highly appreciated! 

P.S. I really hope that it can also applied to reduced genome sequencing like my case!

Best regards,
Han Xiao

**Comment by JimWhiting91** [comment]
Hi Han,

There shouldn't be any problem with running this over a RAD vcf, so hopefully we can get it working for you. Similarly there shouldn't be any issue with your vcf being mapped to a scaffold-level assembly, but bear in mind it only really makes sense to make these plots within scaffolds/chr (it's fine to parse a scaffold id to `chr=`).

It sounds like your VCF file is maybe not sorted? Can you try sorting again with `bcftools sort your_vcf.vcf.gz`.

In terms of preparing a VCF, I have had no problems when using bgzip following by tabix, for example:
```
# zip with bgzip
bgzip -c your_data.vcf > your_data.vcf.gz

# index with tabix
tabix -f -p vcf your_data.vcf.gz
```
The index you're looking for has .gz.tbi suffix, but the vcf will need to be sorted before indexing.

Please let me know if this works for you, otherwise I can have another think.

Cheers,
Jim

**Comment by HanXiaoEvo** [comment]
Hi Jim,

Thank you very much for your super fast reply! 

So I did the sort and the error is like this one: 
Contig 'NC_000861.1' is not defined in the header. (Quick workaround: index the file with tabix.)
But then when I try to index with tabix the error is again Chromosome blocks not continuous.

Here I show you the head of my vcf:

#fileformat=VCFv4.2
##fileDate=20201027
##source="Stacks v2.41"
##INFO=<ID=AD,Number=R,Type=Integer,Description="Total Depth for Each Allele">
##INFO=<ID=AF,Number=A,Type=Float,Description="Allele Frequency">
##INFO=<ID=DP,Number=1,Type=Integer,Description="Total Depth">
##INFO=<ID=NS,Number=1,Type=Integer,Description="Number of Samples With Data">
##FORMAT=<ID=AD,Number=R,Type=Integer,Description="Allele Depth">
##FORMAT=<ID=DP,Number=1,Type=Integer,Description="Read Depth">
##FORMAT=<ID=HQ,Number=2,Type=Integer,Description="Haplotype Quality">
##FORMAT=<ID=GL,Number=G,Type=Float,Description="Genotype Likelihood">
##FORMAT=<ID=GQ,Number=1,Type=Integer,Description="Genotype Quality">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##INFO=<ID=loc_strand,Number=1,Type=Character,Description="Genomic strand the corresponding Sta
#CHROM         POS            ID             REF            ALT            QUAL           FILTE
NC_036838.1    180703         528:102:+      T              A              .              PASS
NC_036838.1    180892         541:250:-      C              T              .              PASS
NC_036838.1    314291         899:20:-       T              G              .              PASS
NC_036838.1    514770         1302:98:-      G              A              .              PASS
NC_036838.1    1144254        2790:55:-      T              C              .              PASS
NC_036838.1    1301170        3081:62:+      C              T              .              PASS
NC_036838.1    1389371        3303:86:-      A              G              .              PASS
NC_036838.1    1486294        3591:245:-     G              T              .              PASS
NC_036838.1    1527477        3763:183:+     A              C              .              PASS
NC_036838.1    3064733        7701:67:-      A              C              .              PASS

One more question, should I use snps.vcf or haps.vcf as you mentioned it may matter for culstering?

Thank you very much again!

Best regards,
Han

**Comment by JimWhiting91** [comment]
Hi Han,

Ok I think I understand the problem, it seems as though bcftools doesn't like how stacks formats vcfs, specifically it doesn't like that stacks doesn't include contig identifiers in the vcf header as is standard with other SNP calling pipelines.

It shouldn't matter so long as you have a `.gz.tbi` index file, but similarly it won't let you index until you've sorted, and you can't sort until you've indexed, so really it's an unfortunate bcftools loop!

The good news is that if you have vcftools installed, you should be able to sort using that, so for eg. `vcf-sort your_data.vcf > your_data_sorted.vcf`. You can then bgzip and tabix the sorted VCF. I've managed to find some stacks VCFs and this has worked for me. I've also run genotype_plot over this stacks vcf to confirm there's no issue and all seems good.

Give that a go and let me know how it goes.

Cheers,
Jim

**Comment by HanXiaoEvo** [comment]
Hi Jim,
Thanks a lot and it works to read in the file!
However, there is still an error that I have no idea (sorry to take your time into this endless debugging)

So I tried both, with or without chr="XXX" (I was thinking that for RADSeq there is just up to 10000 SNPs so may not need to choose the scaffold)
Then it printed the same as:
Scanning file to determine attributes.
File attributes:
  meta lines: 1183
  header_line: 1184
  variant count: 0
  column count: 131
Meta line 1183 read in.
All meta lines processed.
gt matrix initialized.
Character matrix gt created.
  Character matrix gt rows: 0
  Character matrix gt cols: 131
  skip: 0
  nrows: 0
  row_num: 0
Processed variant: 0
All variants processed
Error in x@gt[i, j, drop = FALSE] : subscript out of bounds

Is it about the start and end I set? I didn´t change it as your tutorial. 

Best regards,
Han

**Comment by JimWhiting91** [comment]
Hi Han,

So you'll need to make sure that `start` and `end` correspond to positions on the actual scaffold you're trying to plot, and make sure that `chr=` is set to a scaffold ID in your vcf. If you want to plot the whole scaffold, you can just set `start=1` and set `end=1e8` or any other very large value (or just set `end=` as the length of the scaffolds if you have this info, both should work). This is because the call to bcftools filters the vcf on the basis of the region `chr:start-end`. So if you've left start and end as they are in the tutorial, and these are larger than your scaffold, then you'll end up with an empty vcf which is what it is then reading in (see `variant count: 0`).

Cheers,
Jim

**Comment by HanXiaoEvo** [comment]
HI Jim,

I see, I should have thought about it!
So I did it with the first scaffold and got the correct number of variants. But I got the same error still:
What I wrote:
new_plot <- genotype_plot(vcf="sort_thingva.snps.vcf.gz",
                          chr="NC_000861.1",
                          start=1,
                          end=15168,
                          popmap=popmap,
                          cluster=FALSE,
                          snp_label_size=1e5,
                          colour_scheme=c("#d4b9da","#e7298a","#980043"))

What I got:
Scanning file to determine attributes.
File attributes:
  meta lines: 1183
  header_line: 1184
  variant count: 5
  column count: 131
Meta line 1183 read in.
All meta lines processed.
gt matrix initialized.
Character matrix gt created.
  Character matrix gt rows: 5
  Character matrix gt cols: 131
  skip: 0
  nrows: 5
  row_num: 0
Processed variant: 5
All variants processed
Error in x@gt[i, j, drop = FALSE] : subscript out of bounds

Is there still anything missing? Thank you very much!

Best regards,
Han

**Comment by JimWhiting91** [comment]
So looks like its now reading in your scaffold vcf fine (although only 5 snps), but its still erroring at a subsetting step. Can you share your popmap that you're using? It's worth definitely making sure that all the individual ids in `popmap[,1]` are in your vcf (can check with `bcftools query -l your_vcf.gz`)

Cheers,
Jim

**Comment by HanXiaoEvo** [comment]
Sure, I did bcftools query -l your_vcf.gz | wc -l, there are 122 samples, I did also check the popmap, 123 (plus header). Actually in Stacks it used a popmap to call SNPs so I used the same popmap just added the header.

Well so if you don't mind, I can send the vcf-related files and popmap to your email to check. 
I will suggest closing this issue as the read-in process is mostly done and you solved that part already!
Thank you very much!

Best regards,
Han

**Comment by JimWhiting91** [comment]
Right, so the popmap format is the same as stacks so that should be fine. You shouldn't need a header technically, so there should only be 122 rows when you run `nrow(popmap)`. If all of that is correct though I'm not sure. If you want to email me a small subset of the vcf with a few snps and the popmap I'll see if I can make sense of it, thanks! (my emails here: https://biosciences.exeter.ac.uk/staff/profile/index.php?web_id=James_Whiting)

**Comment by HanXiaoEvo** [comment]
Well I tried twice but keep getting the message that there might be virus in my email and can not be delivered haha...Do you have any other email address or another way to send the files?

**Comment by JimWhiting91** [comment]
Ah yes, I seem to have a memory that emails think that vcf files are viruses for some reason. Maybe try compressing the vcf and popmap to a zip file or tar and try that? Alternatively if you don't mind uploading into this thread that might also work

**Comment by HanXiaoEvo** [comment]
Thanks for all your help and it works with all the effort! I will set another computer and try to repeat what you did!

**Comment by JimWhiting91** [comment]
For those finding this issue in the future, I am aware of two reasons why you may be seeing:
```
Error in x@gt[i, j, drop = FALSE] : subscript out of bounds
```
The first of these is that an individual ID in your popmap is not in your VCF. This causes the issue because the vcf is subsetted according to the popmap, and the subsetting fails (is out of bounds) if an individual ID is not in the VCF. Please check your popmaps for typos (including whitespace) and make sure the expected individuals are all in your vcf. I plan to include an error message to catch this particular issue soon.

If problems persist, the issue can stem from an outdated R version. I am using version 4.0.2, but I have been seeing this error message crop up in older R versions and be resolved by updated.
