### ISSUE TITLE
Plotting Error

### ISSUE THREAD

**Issue by ccastane9** [JimWhiting91/genotype_plot#9]
Hi, 

I'm trying to view the genotype plot, however I always get this error this error: Error: Insufficient values in manual scale. 13 needed but only 3 provided. If I run cluster = TRUE, then I can view the dendograms perfectly although I still get the same error with trying to view the genotype plot. I'm sure it's a small thing that I'm not typing in correctly or changing in your provided script :
geno_and_labels <- cowplot::plot_grid(new_plot$positions,
+                                       new_plot$genotypes,
+                                       axis="tblr",align="v",nrow=9,ncol=2,rel_heights=c(1,9))

I have 9 individuals, and the new_plot generated by GenotypePlot has 4 elements, so I assume that is why the error says that 13 is needed. Could you please help? Below is a more details on the error message I received. I do have ggplot2 installed/activated.

Error: Insufficient values in manual scale. 13 needed but only 3 provided.
Run `rlang::last_error()` to see where the error occurred.
> rlang::last_error()
<error/rlang_error>
Insufficient values in manual scale. 13 needed but only 3 provided.
Backtrace:
  1. (function (x, ...) ...
  2. ggplot2:::print.ggplot(x)
  4. ggplot2:::ggplot_build.ggplot(x)
  5. base::lapply(data, scales_map_df, scales = npscales)
  6. ggplot2:::FUN(X[[i]], ...)
  8. base::lapply(scales$scales, function(scale) scale$map_df(df = df))
  9. ggplot2:::FUN(X[[i]], ...)
 10. scale$map_df(df = df)
 11. ggplot2:::f(..., self = self)
 12. base::lapply(aesthetics, function(j) self$map(df[[j]]))
 13. ggplot2:::FUN(X[[i]], ...)
 14. self$map(df[[j]])
 15. ggplot2:::f(..., self = self)
 16. self$palette(n)
 17. ggplot2:::f(...)
Run `rlang::last_trace()` to see the full context.

**Comment by jsalt** [comment]
Hi there,

I'm getting the same error. Any guidance on how this was fixed?

Thanks!

**Comment by JimWhiting91** [comment]
Hi!

Sorry I must have missed this at the time, the above error looks like its caused by trying to plot a VCF with multi-allelic SNPs without either removing these before plotting, or telling genotypeplot to treat the VCF as if it's multi-allelic. The "3 provided" here:
```{r}
Insufficient values in manual scale. 13 needed but only 3 provided.
```
is with respect to the three colours given to plot 0/0, 0/1 and 1/1 genotypes. So the error here is saying that 13 are needed, because 13 possible genotypes exist in the VCF rather than the three that is expected for biallelic sites.

Hope this helps, and again apologies for having missed the initial comment.

Jim

**Comment by jsalt** [comment]
That fixed it, thanks so much!!
